import React from 'react';
import styles from '../settings.module.css';

export function AboutTab() {
    return (
        <div>
            <h2>About</h2>
            <p style={{ margin: '12px 0' }}>
                <strong>Created By:</strong> <a href="https://filipkin.com">Filip Kin</a><br />
                <strong>Contributors:</strong> <a href="https://soren.thezaisers.me/">Soren Zaiser</a>
            </p>
            <p style={{ margin: '12px 0', lineHeight: 1.6 }}>
                This application hosts a web page with captions generated by the Google Speech-to-Text API from an
                audio input stream on a magenta (or whatever hex color you desire) background to be chroma keyed
                and overlayed in vMix. Multiple inputs can be added and each can be set to display as a different
                color. Each input stream has an adjustable threshold, and includes a configurable profanity filter.
            </p>
            <pre className={styles.aboutPre}>{`LICENSE
Copyright (c) 2023, Filip Kin
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:
1. Redistributions of source code must retain the above copyright
   notice, this list of conditions and the following disclaimer.
2. Redistributions in binary form must reproduce the above copyright
   notice, this list of conditions and the following disclaimer in the
   documentation and/or other materials provided with the distribution.
3. All advertising materials mentioning features or use of this software
   must display the following acknowledgement:
   This product includes software developed by Filip Kin.
4. Neither the name of Filip Kin nor the names of its contributors may be
   used to endorse or promote products derived from this software without
   specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDER ''AS IS'' AND ANY EXPRESS
OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.`}</pre>
        </div>
    );
}
